// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiftBuilds.Data;

#nullable disable

namespace RiftBuilds.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20261007182121_SeedChampions")]
    partial class SeedChampions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiftBuilds.Models.Build", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChampionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChampionId");

                    b.ToTable("Builds");
                });

            modelBuilder.Entity("RiftBuilds.Models.BuildItem", b =>
                {
                    b.Property<int>("BuildId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Slot")
                        .HasColumnType("int");

                    b.HasKey("BuildId", "ItemId");

                    b.HasIndex("ItemId");

                    b.ToTable("BuildItems");
                });

            modelBuilder.Entity("RiftBuilds.Models.Champion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Champions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A versatile champion who switches between ranged combat and a powerful melee transformation.",
                            ImageUrl = "/images/champions/gnar.jpg",
                            Name = "Gnar"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A mobile swordsman who uses wind techniques and precise attacks to defeat his enemies.",
                            ImageUrl = "/images/champions/yasuo.jpg",
                            Name = "Yasuo"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A durable champion who locks down enemies and helps his team with powerful crowd control.",
                            ImageUrl = "/images/champions/amumu.jpg",
                            Name = "Amumu"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A ranged damage dealer who switches weapons and becomes increasingly dangerous during team fights.",
                            ImageUrl = "/images/champions/jinx.jpg",
                            Name = "Jinx"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A support champion who protects allies with shields and empowers them with magical abilities.",
                            ImageUrl = "/images/champions/lulu.jpg",
                            Name = "Lulu"
                        });
                });

            modelBuilder.Entity("RiftBuilds.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("RiftBuilds.Models.Build", b =>
                {
                    b.HasOne("RiftBuilds.Models.Champion", "Champion")
                        .WithMany("Builds")
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Champion");
                });

            modelBuilder.Entity("RiftBuilds.Models.BuildItem", b =>
                {
                    b.HasOne("RiftBuilds.Models.Build", "Build")
                        .WithMany("BuildItems")
                        .HasForeignKey("BuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiftBuilds.Models.Item", "Item")
                        .WithMany("BuildItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Build");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RiftBuilds.Models.Build", b =>
                {
                    b.Navigation("BuildItems");
                });

            modelBuilder.Entity("RiftBuilds.Models.Champion", b =>
                {
                    b.Navigation("Builds");
                });

            modelBuilder.Entity("RiftBuilds.Models.Item", b =>
                {
                    b.Navigation("BuildItems");
                });
#pragma warning restore 612, 618
        }
    }
}
